  name: Hello World!

  on:
    push:
      branches:
        - main

  jobs:
    hello_world_job:
      runs-on: ubunto-latest
      steps:
        - name: Say hello
          run: |
            echo "Hello World!"
